/* Product state is separate from the shared JANO interface look. */
(()=>{'use strict';
const $=id=>document.getElementById(id),E=FinishEngine,clone=v=>JSON.parse(JSON.stringify(v)),pause=()=>new Promise(r=>setTimeout(r,0));
let lang='de';try{lang=localStorage.getItem('finish.language')||'de';}catch{}if(!FinishText[lang])lang='de';
const t=(key,vars={})=>Object.entries(vars).reduce((s,[k,v])=>s.replaceAll('{'+k+'}',String(v)),FinishText[lang][key]||key);
let images=[],active=-1,global=E.defaults(),lut=null,lutName='',logo=null,logoBlob=null,logoName='',busy=false,cancelled=false,revision=0,drawTimer,boxes={},lookUi;
let brand={logo:{x:1,y:1,size:16,opacity:100,margin:3},text:{x:0,y:1,size:2.4,opacity:100,margin:3},caption:'',font:'Segoe UI',bold:false,textColor:'#ffffff',shape:'none',shapeColor:'#ffffff',shapeOpacity:40};
const native=!!window.chrome?.webview;document.body.classList.toggle('desktop',native);
const rpcPending=new Map();let serial=0;
function rpc(op,data={}){return new Promise((resolve,reject)=>{if(!native)return reject(Error(t('nativeRequired')));const id=++serial;rpcPending.set(id,{resolve,reject});chrome.webview.postMessage({channel:'finish',id,op,...data});});}
if(native)chrome.webview.addEventListener('message',e=>{const m=e.data;if(m.channel!=='finish')return;const p=rpcPending.get(m.id);if(!p)return;rpcPending.delete(m.id);m.ok?p.resolve(m.result):p.reject(Error(m.error));});
function status(key,vars={},error=false){$('status').textContent=t(key,vars);$('status').classList.toggle('error',error);}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function setBusy(value){busy=value;document.body.classList.toggle('busy',value);document.querySelector('main').inert=value;document.querySelector('header').inert=value;$('progress').hidden=!value;$('cancelJob').hidden=!value;$('exportOpen').disabled=value||!images.some(i=>i.selected);if(!value)$('progress').value=0;}
function current(){return active>=0?(images[active].settings||global):global;}
function change(key,value){if(busy)return;if($('scope').value==='single'&&active>=0){images[active].settings={...current(),[key]:value};}else{global[key]=value;for(const item of images)if(item.settings)item.settings[key]=value;}schedule();syncControls();renderList();}
const sliders=[['auto',0,100,1],['exposure',-2,2,.05],['temperature',-100,100,1],['tint',-100,100,1],['contrast',-70,70,1],['highlights',-100,100,1],['shadows',-100,100,1],['saturation',-100,100,1]];
function slider(parent,id,key,min,max,step,value,onchange){const label=el('label','slider');label.htmlFor=id;const head=el('span','slider-head'),name=el('span',null,t(key)),out=el('output');name.dataset.t=key;out.id=id+'Value';head.append(name,out);const input=el('input');input.type='range';Object.assign(input,{id,min,max,step,value});out.value=value;input.oninput=()=>{out.value=input.value;onchange(Number(input.value));};label.append(head,input);parent.append(label);return input;}
for(const [key,min,max,step]of sliders)slider($('sliders'),key,key,min,max,step,global[key],v=>change(key,v));
for(const type of ['logo','text']){
 const p=$(type+'Controls');slider(p,type+'Size',type==='logo'?'width':'fontSize',type==='logo'?2:.5,type==='logo'?60:10,.1,brand[type].size,v=>{brand[type].size=v;schedule();});
 slider(p,type+'Opacity','opacity',0,100,1,100,v=>{brand[type].opacity=v;schedule();});slider(p,type+'Margin','margin',0,15,.5,3,v=>{brand[type].margin=v;schedule();});
 const group=el('div','anchor-grid');group.setAttribute('role','group');group.dataset.type=type;p.append(group);
 for(let n=0;n<9;n++){const b=el('button','j-btn');b.type='button';b.dataset.n=n;b.append(el('i'));b.onclick=()=>{brand[type].x=(n%3)/2;brand[type].y=Math.floor(n/3)/2;syncBrand();schedule();};group.append(b);}
 slider(p,type+'X','horizontal',0,100,1,brand[type].x*100,v=>{brand[type].x=v/100;schedule();});slider(p,type+'Y','vertical',0,100,1,brand[type].y*100,v=>{brand[type].y=v/100;schedule();});
}
function translate(){document.documentElement.lang=lang;$('language').value=lang;document.querySelectorAll('[data-t]').forEach(n=>n.textContent=t(n.dataset.t));document.querySelectorAll('.anchor-grid button').forEach(b=>{b.title=t('anchor',{n:Number(b.dataset.n)+1});b.setAttribute('aria-label',b.title);});lookUi?.translate();renderList();renderCards();syncControls();status('ready');if(native)rpc('language',{value:lang}).catch(()=>{});}
function syncControls(){const s=current();for(const [key]of sliders){$(key).value=s[key];$(key+'Value').value=s[key];}$('intensity').value=s.intensity;$('intensityValue').value=s.intensity+'%';$('autoMode').value=s.autoMode;document.querySelectorAll('.look-card').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.look===s.look)));$('lutName').textContent=lutName||t('lutHint');$('resetSingle').disabled=active<0||!images[active].settings;}
function syncBrand(){for(const type of ['logo','text']){for(const [suffix,key,mul]of [['Size','size',1],['Opacity','opacity',1],['Margin','margin',1],['X','x',100],['Y','y',100]]){$(type+suffix).value=brand[type][key]*mul;$(type+suffix+'Value').value=Math.round(brand[type][key]*mul*10)/10;}document.querySelectorAll('.anchor-grid[data-type='+type+'] button').forEach(b=>{const n=Number(b.dataset.n);b.setAttribute('aria-pressed',String(brand[type].x===(n%3)/2&&brand[type].y===Math.floor(n/3)/2));});}for(const k of ['caption','font','textColor','shape','shapeColor','shapeOpacity'])$(k).value=brand[k];$('bold').checked=brand.bold;$('logoName').textContent=logoName;}
function renderList(){const list=$('images');list.replaceChildren();images.forEach((item,i)=>{const row=el('div','thumb'+(i===active?' active':''));row.setAttribute('role','listitem');const button=el('button');button.title=item.name;button.setAttribute('aria-label',item.name);const im=el('img');im.src=item.thumb;im.alt='';const label=el('span',null,item.name+(item.settings?' •':''));button.append(im,label);button.onclick=()=>{active=i;syncControls();renderList();schedule();renderCards();};const check=el('input');check.type='checkbox';check.checked=item.selected;check.setAttribute('aria-label',t('export')+' '+item.name);check.onchange=()=>{item.selected=check.checked;counts();};row.append(button,check);list.append(row);});counts();}
function counts(){const n=images.filter(i=>i.selected).length;$('count').textContent=images.length;$('selectedCount').textContent=t('selected',{n,total:images.length});$('exportOpen').disabled=!n||busy;}
function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
async function decode(blob){const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>80000000||!img.naturalWidth)throw Error('size');return img;}finally{URL.revokeObjectURL(url);}}
async function addFiles(files){if(busy)return;const source=Array.from(files);if(images.length+source.length>100){status('limit',{},true);return;}setBusy(true);cancelled=false;status('loading');let added=0,errors=[];try{for(const file of source){if(cancelled)break;try{if(!/\.(jpe?g|png)$/i.test(file.name))throw Error('type');const img=await decode(file);const scale=Math.min(1,480/Math.max(img.naturalWidth,img.naturalHeight)),c=canvas(Math.round(img.naturalWidth*scale),Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,c.width,c.height);const analysis=E.analyze(ctx.getImageData(0,0,c.width,c.height).data);images.push({file,name:file.name,w:img.naturalWidth,h:img.naturalHeight,thumb:c.toDataURL('image/png'),analysis,settings:null,selected:true});added++;}catch{errors.push(file.name);}$('progress').value=100*(added+errors.length)/source.length;await pause();}if(active<0&&images.length)active=0;renderList();syncControls();renderCards();schedule();status(errors.length?'importError':'imported',errors.length?{name:errors.join(', ')}:{n:added},!!errors.length);}finally{setBusy(false);}}
function renderCards(){const parent=$('lookCards');parent.replaceChildren();for(const key of ['neutral','warm','cool','soft','crisp','mono',...(lut?['custom']:[])]){const b=el('button','look-card');b.dataset.look=key;b.setAttribute('aria-pressed',String(current().look===key));const c=canvas(140,70);b.append(c,el('span',null,t(key)));b.onclick=()=>change('look',key);parent.append(b);const ctx=c.getContext('2d');if(active>=0){const img=new Image();img.onload=()=>{ctx.drawImage(img,0,0,140,70);const pixels=ctx.getImageData(0,0,140,70);E.transform(pixels.data,{...E.defaults(),look:key,intensity:100},0,lut);ctx.putImageData(pixels,0,0);};img.src=images[active].thumb;}else{const gr=ctx.createLinearGradient(0,0,140,70);gr.addColorStop(0,'#83908b');gr.addColorStop(1,'#2a343e');ctx.fillStyle=gr;ctx.fillRect(0,0,140,70);const px=ctx.getImageData(0,0,140,70);E.transform(px.data,{...E.defaults(),look:key,intensity:100},0,lut);ctx.putImageData(px,0,0);}}parent.style.gridTemplateColumns='repeat('+(lut?7:6)+',minmax(0,1fr))';}
function rect(type,w,h,bw,bh){const a=brand[type],m=Math.min(w,h)*a.margin/100;return {x:m+Math.max(0,w-bw-2*m)*a.x,y:m+Math.max(0,h-bh-2*m)*a.y,w:bw,h:bh};}
function branding(c){const ctx=c.getContext('2d'),w=c.width,h=c.height,m=Math.min(w,h)*.03;const hit={};ctx.save();ctx.fillStyle=ctx.strokeStyle=brand.shapeColor;ctx.globalAlpha=brand.shapeOpacity/100;ctx.lineWidth=Math.max(1,w/1000);
 if(brand.shape==='bar')ctx.fillRect(0,h-h*.14,w,h*.14);
 if(brand.shape==='frame')ctx.strokeRect(m,m,w-2*m,h-2*m);
 if(brand.shape==='line'){ctx.beginPath();ctx.moveTo(m,h-m*2);ctx.lineTo(w-m,h-m*2);ctx.stroke();}
 if(brand.shape==='grid'||brand.shape==='dots'){const sz=Math.min(w,h)*.13,step=sz/5,x=w-m-sz,y=m;if(brand.shape==='grid'){ctx.beginPath();for(let i=0;i<=5;i++){ctx.moveTo(x+i*step,y);ctx.lineTo(x+i*step,y+sz);ctx.moveTo(x,y+i*step);ctx.lineTo(x+sz,y+i*step);}ctx.stroke();}else for(let i=0;i<=5;i++)for(let j=0;j<=5;j++){ctx.beginPath();ctx.arc(x+i*step,y+j*step,Math.max(.7,w/1500),0,Math.PI*2);ctx.fill();}}
 ctx.restore();if(logo){const margin=Math.min(w,h)*brand.logo.margin/100;let bw=w*brand.logo.size/100,bh=bw*logo.naturalHeight/logo.naturalWidth;const f=Math.min(1,(w-margin*2)/bw,(h-margin*2)/bh);bw*=f;bh*=f;const r=rect('logo',w,h,bw,bh);ctx.save();ctx.globalAlpha=brand.logo.opacity/100;ctx.drawImage(logo,r.x,r.y,r.w,r.h);ctx.restore();hit.logo=r;}
 if(brand.caption.trim()){ctx.save();const margin=Math.min(w,h)*brand.text.margin/100,maxW=w-2*margin,maxH=h-2*margin;let fs=w*brand.text.size/100,lines=brand.caption.split('\n');const font=()=>`${brand.bold?'600':'400'} ${fs}px "${brand.font}"`;ctx.font=font();let bw=Math.max(...lines.map(line=>ctx.measureText(line).width)),bh=lines.length*fs*1.3;const f=Math.min(1,maxW/Math.max(1,bw),maxH/bh);fs*=f;bw*=f;bh*=f;ctx.font=font();const r=rect('text',w,h,bw,bh);ctx.fillStyle=brand.textColor;ctx.globalAlpha=brand.text.opacity/100;ctx.textBaseline='top';lines.forEach((line,i)=>ctx.fillText(line,r.x,r.y+i*fs*1.3));ctx.restore();hit.text=r;}return hit;
}
async function render(item,maxEdge,original=false,token=null){const img=await decode(item.file);const ratio=maxEdge?Math.min(1,maxEdge/Math.max(item.w,item.h)):1,c=canvas(Math.max(1,Math.round(item.w*ratio)),Math.max(1,Math.round(item.h*ratio))),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,c.width,c.height);if(original)return {c,hit:{}};const s=clone(item.settings||global),pixels=ctx.getImageData(0,0,c.width,c.height),ev=s.autoMode==='series'?(images[0]?.analysis||0):item.analysis;for(let start=0;start<pixels.data.length;start+=262144){if(token!==null&&token!==revision)throw Error('stale');if(busy&&cancelled)throw Error('cancelled');E.transform(pixels.data,s,ev,lut,start,Math.min(start+262144,pixels.data.length));await pause();}ctx.putImageData(pixels,0,0);return {c,hit:branding(c)};}
function schedule(){revision++;clearTimeout(drawTimer);drawTimer=setTimeout(preview,90);}
async function preview(){const token=revision;if(active<0){$('preview').hidden=true;$('empty').hidden=false;$('imageName').textContent=t('emptyTitle');$('dimensions').textContent='';return;}const item=images[active];$('imageName').textContent=item.name;$('dimensions').textContent=`${item.w} × ${item.h} px · sRGB`;$('previewHint').textContent=t('pending');try{const {c,hit}=await render(item,1400,$('before').checked,token);if(token!==revision)return;const p=$('preview');p.width=c.width;p.height=c.height;p.getContext('2d').drawImage(c,0,0);boxes=hit;p.hidden=false;$('empty').hidden=true;$('previewHint').textContent=t('previewHint');}catch(e){if(e.message!=='stale'&&e.message!=='cancelled')status('failed',{detail:e.message},true);}}
let drag=null;$('preview').addEventListener('pointerdown',e=>{if(busy||$('before').checked)return;const r=$('preview').getBoundingClientRect(),x=(e.clientX-r.left)/r.width*$('preview').width,y=(e.clientY-r.top)/r.height*$('preview').height;for(const type of ['text','logo']){const b=boxes[type];if(b&&x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h){drag={type,x,y,start:clone(brand[type]),box:b};$('preview').setPointerCapture(e.pointerId);break;}}});
$('preview').addEventListener('pointermove',e=>{if(!drag)return;const p=$('preview'),r=p.getBoundingClientRect(),a=brand[drag.type],margin=Math.min(p.width,p.height)*a.margin/100,x=(e.clientX-r.left)/r.width*p.width,y=(e.clientY-r.top)/r.height*p.height;a.x=E.clamp(drag.start.x+(x-drag.x)/Math.max(1,p.width-drag.box.w-2*margin));a.y=E.clamp(drag.start.y+(y-drag.y)/Math.max(1,p.height-drag.box.h-2*margin));syncBrand();schedule();});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('preview').addEventListener(name,()=>drag=null);
async function setLogo(blob,name){const decoded=await decode(blob);logo=decoded;logoBlob=blob;logoName=name;syncBrand();schedule();}
const db=new Promise((resolve,reject)=>{const request=indexedDB.open('jano-rendering-finish-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('templates',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});db.catch(()=>{});
async function store(op,value){const database=await db;return new Promise((resolve,reject)=>{const tx=database.transaction('templates',op==='getAll'?'readonly':'readwrite'),req=tx.objectStore('templates')[op](...(value===undefined?[]:[value]));let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function exportSettings(){return Object.fromEntries(['format','quality','size','background','prefix'].map(id=>[id,$(id).value]));}
async function saveTemplate(){const name=$('templateName').value.trim();if(!name){$('templateStatus').textContent=t('nameError');return;}try{await store('put',{id:crypto.randomUUID(),schema:1,name,settings:clone(current()),brand:clone(brand),logo:logoBlob,logoName,lut:clone(lut),lutName,export:exportSettings()});$('templateStatus').textContent=t('saved');$('templateName').value='';await listTemplates();}catch{$('templateStatus').textContent=t('storageError');}}
async function loadTemplate(item){let decoded=null;if(item.logo)decoded=await decode(item.logo);global=clone(item.settings);brand=clone(item.brand);lut=clone(item.lut);lutName=item.lutName;logo=decoded;logoBlob=item.logo;logoName=item.logoName;for(const image of images)image.settings=null;for(const [k,v]of Object.entries(item.export))$(k).value=v;$('qualityValue').value=$('quality').value+'%';$('quality').disabled=$('format').value==='png';$('background').disabled=$('format').value==='png';syncBrand();syncControls();renderCards();renderList();schedule();$('templateStatus').textContent=t('loaded');}
async function listTemplates(){const list=$('templateList');try{const items=await store('getAll');list.replaceChildren();if(!items.length)list.append(el('p','j-muted',t('emptyTemplates')));for(const item of items.sort((a,b)=>a.name.localeCompare(b.name))){const row=el('div','template-row');const load=el('button','j-btn',t('load')),del=el('button','j-btn j-btn-danger',t('delete'));load.onclick=()=>loadTemplate(item).catch(e=>{$('templateStatus').textContent=t('failed',{detail:e.message});});del.onclick=async()=>{if(del.dataset.confirm!=='yes'){del.dataset.confirm='yes';del.textContent=t('confirmDelete');return;}try{await store('delete',item.id);await listTemplates();}catch{$('templateStatus').textContent=t('storageError');}};row.append(el('span',null,item.name),load,del);list.append(row);}}catch{$('templateStatus').textContent=t('storageError');}}
async function dataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
async function doExport(test=false){if(busy)return;const chosen=images.filter(i=>i.selected);if(!chosen.length){status('noSelection',{},true);return;}const opts=exportSettings();cancelled=false;setBusy(true);revision++;clearTimeout(drawTimer);let count=0,folder='';try{status('chooseFolder');folder=await rpc(test?'testFolder':'chooseFolder');if(!folder){status('cancelled',{n:0});return;}$('exportDialog').close();for(let i=0;i<chosen.length;i++){if(cancelled)break;const item=chosen[i];status('exporting',{n:i+1,total:chosen.length,name:item.name});const {c}=await render(item,Number(opts.size));if(cancelled)break;if(opts.format==='jpg'){const ctx=c.getContext('2d');ctx.globalCompositeOperation='destination-over';ctx.fillStyle=opts.background;ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='source-over';}const blob=await new Promise(resolve=>c.toBlob(resolve,opts.format==='png'?'image/png':'image/jpeg',Number(opts.quality)/100));if(!blob)throw Error('Image encoder failed');const encoded=await dataUrl(blob);await rpc('save',{name:E.filename(item.name,opts.prefix,i,opts.format),data:encoded});count++;$('progress').value=count/chosen.length*100;}status(cancelled?'cancelled':'done',{n:count,folder});return {count,folder};}catch(e){if(e.message==='cancelled'){status('cancelled',{n:count});return {count,folder};}status('exportFailed',{n:count,detail:e.message},true);throw e;}finally{setBusy(false);schedule();}}
$('import').onclick=$('emptyImport').onclick=()=>$('files').click();$('files').onchange=e=>{addFiles(e.target.files);e.target.value='';};
document.addEventListener('dragover',e=>{e.preventDefault();if(!busy)$('stage').classList.add('drag');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('stage').classList.remove('drag');});document.addEventListener('drop',e=>{e.preventDefault();$('stage').classList.remove('drag');addFiles(e.dataTransfer.files);});
$('selectAll').onclick=()=>{images.forEach(i=>i.selected=true);renderList();};$('remove').onclick=()=>{images=images.filter(i=>!i.selected);active=images.length?0:-1;renderList();renderCards();syncControls();schedule();status('removed');};
$('scope').onchange=syncControls;$('before').onchange=schedule;$('autoMode').onchange=e=>change('autoMode',e.target.value);$('intensity').oninput=e=>change('intensity',Number(e.target.value));
$('reset').onclick=()=>{if($('scope').value==='single'&&active>=0)images[active].settings=E.defaults();else{global=E.defaults();images.forEach(i=>i.settings=null);}syncControls();renderList();schedule();status('resetDone');};$('resetSingle').onclick=()=>{if(active>=0)images[active].settings=null;syncControls();renderList();schedule();};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('imagePanel').hidden=b.dataset.tab!=='image';$('brandPanel').hidden=b.dataset.tab!=='brand';});
$('lutImport').onclick=()=>$('lutFile').click();$('lutFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20000000)throw Error();const next=E.parseCube(await file.text());lut=next;lutName=file.name;change('look','custom');renderCards();status('lutLoaded',{name:file.name});}catch{status('cubeError',{},true);}};
$('logoImport').onclick=()=>$('logoFile').click();$('logoFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!/\.png$/i.test(file.name)||file.type!=='image/png')throw Error();await setLogo(file,file.name);}catch{status('logoError',{},true);}};$('logoRemove').onclick=()=>{logo=logoBlob=null;logoName='';syncBrand();schedule();};
for(const key of ['caption','font','textColor','shape','shapeColor','shapeOpacity'])$(key).oninput=e=>{brand[key]=key==='shapeOpacity'?Number(e.target.value):e.target.value;schedule();};$('bold').onchange=e=>{brand.bold=e.target.checked;schedule();};
$('language').onchange=e=>{lang=e.target.value;try{localStorage.setItem('finish.language',lang);}catch{}translate();syncBrand();schedule();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('templatesOpen').onclick=()=>{$('templateStatus').textContent='';$('templateDialog').showModal();listTemplates();};$('templateSave').onclick=saveTemplate;
$('exportOpen').onclick=()=>{$('exportSummary').textContent=t('summary',{n:images.filter(i=>i.selected).length});$('exportDialog').showModal();};$('exportForm').onsubmit=e=>{e.preventDefault();doExport().catch(()=>{});};$('quality').oninput=e=>$('qualityValue').value=e.target.value+'%';$('format').onchange=()=>{$('quality').disabled=$('format').value==='png';$('background').disabled=$('format').value==='png';};$('cancelJob').onclick=()=>{cancelled=true;};
lookUi=JanoLooks.mount({app:'rendering-finish',legacyKey:'finish.look.v1',trigger:$('lookOpen'),dialog:$('lookDialog'),language:()=>lang});
translate();syncBrand();
// Isolated native test entry: same import, rendering, persistence and export paths.
window.FinishQA={async run(){
 const assert=(v,m)=>{if(!v)throw Error(m);};let files=[];for(let i=0;i<10;i++){const c=canvas(480+i*10,300);const ctx=c.getContext('2d');ctx.fillStyle=['#647579','#a59b84','#3b4f63'][i%3];ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#d8d3c7';ctx.fillRect(30,35,180,160);ctx.fillStyle='#23373a';ctx.fillRect(245,110,160,120);ctx.clearRect(0,0,8,8);const blob=await new Promise(r=>c.toBlob(r,'image/png'));files.push(new File([blob],'Rendering_'+String(i+1).padStart(2,'0')+'.png',{type:'image/png'}));}await addFiles(files);assert(images.length===10,'batch import');
 const lc=canvas(200,70),lx=lc.getContext('2d');lx.fillStyle='#ffffff';lx.fillRect(5,5,190,60);lx.fillStyle='#1c2024';lx.font='bold 32px Arial';lx.fillText('STUDIO',24,48);await setLogo(await new Promise(r=>lc.toBlob(r)),'Testlogo.png');brand.caption='Projekt / 2026';brand.shape='line';syncBrand();change('auto',35);change('look','warm');change('exposure',.1);$('scope').value='single';change('exposure',.45);assert(images[0].settings.exposure===.45&&global.exposure===.1,'individual correction');$('scope').value='all';
 $('templateName').value='QA Kundenvorlage';await saveTemplate();const rows=await store('getAll');assert(rows.length>0&&rows[0].logo,'template persists embedded logo');await loadTemplate(rows[0]);assert(logo&&brand.caption==='Projekt / 2026','template readback');lang='en';translate();assert(brand.caption==='Projekt / 2026'&&images.length===10,'language retains data');lang='de';translate();
 $('format').value='png';$('size').value='0';const result=await doExport(true);assert(result.count===10,'batch export');const check=await render(images[0],0);assert(check.c.getContext('2d').getImageData(0,0,1,1).data[3]===0,'alpha retained');$('before').checked=true;const original=await render(images[0],0,true);assert(Object.keys(original.hit).length===0,'before excludes branding');$('before').checked=false;
 $('format').value='jpg';images.forEach((im,i)=>im.selected=i===0);$('size').value='2560';await doExport(true);images.forEach(im=>im.selected=true);$('format').value='png';$('size').value='0';renderList();await preview();
 // Collision handling: a second export must create another file, never replace one.
 images.forEach((im,i)=>im.selected=i===0);await doExport(true);images.forEach(im=>im.selected=true);
 // The real cancel action stops at a chunk boundary with no partial output file.
 const exportPromise=doExport(true);setTimeout(()=>$('cancelJob').click(),1);const abort=await exportPromise;assert(!abort||abort.count===0,'cancel export');
 // A larger JPG input exercises resizing and JPEG decoding in the same pipeline.
 const large=canvas(2600,1500),largeCtx=large.getContext('2d');largeCtx.fillStyle='#74898d';largeCtx.fillRect(0,0,2600,1500);const largeBlob=await new Promise(r=>large.toBlob(r,'image/jpeg',.95));await addFiles([new File([largeBlob],'Large_Render.jpg',{type:'image/jpeg'})]);images.forEach((im,i)=>im.selected=i===10);$('format').value='jpg';$('size').value='1280';await doExport(true);images.pop();active=0;images.forEach(im=>im.selected=true);$('format').value='png';$('size').value='0';
 // Logo pixels stay outside the image grading; transparent corners survive PNG.
 const composed=await render(images[0],0),lp=composed.hit.logo;const pixel=composed.c.getContext('2d').getImageData(Math.round(lp.x+lp.w*.12),Math.round(lp.y+lp.h*.2),1,1).data;assert(pixel[0]>245&&pixel[1]>245&&pixel[2]>245,'logo not tinted');
 // Custom LUT remains embedded in a saved template, including after readback.
 const cube=['LUT_3D_SIZE 2'];for(let b=0;b<2;b++)for(let g=0;g<2;g++)for(let r=0;r<2;r++)cube.push(`${r} ${g} ${b}`);lut=E.parseCube(cube.join('\n'));lutName='identity.cube';change('look','custom');$('templateName').value='QA LUT';await saveTemplate();const lutTemplate=(await store('getAll')).find(v=>v.name==='QA LUT');assert(lutTemplate.lut.data.length===24,'LUT template data');await loadTemplate(rows[0]);
 renderList();await preview();status('ready');window.__qaResult={ok:true,images:images.length,exported:result.count,templates:2,cancellation:true,resize:true,collision:true,logoUntinted:true};return window.__qaResult;
},state:()=>({images:images.length,brand:clone(brand),settings:clone(global),busy,lang}),render,templates:()=>store('getAll')};
})();
